name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - edited
    paths-ignore:
      # if contracts/** has changed, let the PR be handled by the `pull_contracts` action
      - 'contracts/**'

jobs:
  Validate:
    runs-on: ubuntu-18.04
    steps:
      # https://github.com/actions/checkout
      - name: checkout
        uses: actions/checkout@v2

      - name: install NodeJS
        uses: actions/setup-node@v2

      - name: set NPM version
        run: npm i -g npm@6.14.16

      # build & test
      - name: "install, build, test"
        run: |
          npm ci
          npm run test:ci
          npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}