name: Build and Test

on:
  push:
    branches:
      - main
      - devop/*

jobs:
  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # https://github.com/actions/virtual-environments
        os: [ubuntu-20.04, macos-11, windows-2022]
    steps:
      # https://github.com/actions/checkout
      - name: checkout
        uses: actions/checkout@v2

      - name: install NodeJS
        uses: actions/setup-node@v2

      - name: set NPM version
        run: npm i -g npm@6.14.16

      # build & test
      - name: "install, build, test"
        run: |
          npm ci
          npm run build:prod
          npm run build:test
          npm run test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}